// thanks to https://medium.com/@ConnorFinnegan/how-to-make-a-simple-text-replacement-chrome-extension-3e7aa9fa301f#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImQyNWY4ZGJjZjk3ZGM3ZWM0MDFmMDE3MWZiNmU2YmRhOWVkOWU3OTIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2NzczNjc1NzksImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwMzYyNjI5ODM0Mjg1MzExOTU1OSIsImVtYWlsIjoiYW1lbGlhLnJ1emVrLmtsZWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJuYW1lIjoiQW1lbGlhIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FHTm15eFltdks3QzRZSmJyWmZRTDAycmFMcUZUZzJfNGZVODBGSWNrU2xxU1E9czk2LWMiLCJnaXZlbl9uYW1lIjoiQW1lbGlhIiwiaWF0IjoxNjc3MzY3ODc5LCJleHAiOjE2NzczNzE0NzksImp0aSI6IjRiZTQzMjAwMjE0ZmI1NDBiZWE3ZjgyNGU2MmM5NGI3ZGE0MGU1OTQifQ.GQvaNiJBFXzwf5wUI14RqfZP45jDz57ephJrVbSu_ZjuiZM-EADucoQwbBDwvxziZd810QlaI47sL7TOyHq2wSWGmz8Pld67xS_Dm5bWBCMjbzA1gwAvyjhXruFVuUBAo9dHow7efl7BQQZnBGPMY4jWbkcd4nl2SrfiS7MaViHjEIIQ76NgjRbAEavMR7NGwqt3NQzvmNx2vV3kQ-EGNWFC1spH1zaEYpsz957OxndY3vdyxNlTiS6rJWlIX2p9C3u_Va7trh2EeYMqgG4fwbR4uDtycqShi-IjAtmjs5yR6_1YWDRonVEom3u1NYDxGEEgnYyrdwBYl3zmWQByzw
const text = document.querySelectorAll('h1, h2, h3, h4, h5, p, li, td, caption, span, a')

const translation = new Map ([
['I','我'],
['me','我'],
['us','我们'],
['we','我们'],
['you','你'],
['him','他'],
['he','他'],
['she','她'],
['her','她'],
['they','他们'],
['this','这 (这儿)'],
['here','这 (这儿)'],
['there','那 (那儿)'],
['that','那 (那儿)'],
['where','哪（哪儿）'],
['who','谁'],
['why','什么'],
['what','什么'],
['how much','多少'],
['how many','多少'],
['how many','几'],
['a few','几'],
['how','怎么'],
['how about','怎么样'],
['one','一'],
['two','二'],
['three','三'],
['four','四'],
['five','五'],
['six','六'],
['seven','七'],
['eight','八'],
['nine','九'],
['ten','十'],
['zero','零'],
['a, an','个'],
['year','岁'],
['volume','本'],
['some','些'],
['piece','块'],
['no','不'],
['not','没'],
['quite','很'],
['very','很'],
['too','太'],
['all','都'],
['and','和'],
['in','在'],
['at','在'],
['?','吗'],
['hello','喂'],
['home','家'],
['school','学校'],
['restaurant','饭店'],
['store','商店'],
['hospital','医院'],
['train station','火车站'],
['China','中国'],
['Beijing','北京'],
['up','上'],
['down','下'],
['front','前面'],
['behind','后面'],
['inside','里'],
['today','今天'],
['tomorrow','明天'],
['yesterday','昨天'],
['morning','上午'],
['noon','中午'],
['afternoon','下午'],
['year','年'],
['month','月'],
['day','日'],
['week','星期'],
['dot, spot','点'],
['dot, spot','点'],
['minute','分钟'],
['now','现在'],
['time','时候'],
['father','爸爸'],
['mother','妈妈'],
['son','儿子'],
['daughter','女儿'],
['teacher','老师'],
['student','学生'],
['classmate','同学'],
['friend','朋友'],
['doctor','医生'],
['sir','先生'],
['Miss','小姐'],
['cloth','衣服'],
['water','水'],
['vegetable','菜'],
['rice','米饭'],
['fruit','水果'],
['apple','苹果'],
['tea','茶'],
['cup','杯子'],
['money','钱'],
['airplane','飞机'],
['taxi','出租车'],
['television','电视'],
['computer','电脑'],
['movie','电影'],
['weather','天气'],
['cat','猫'],
['dog','狗'],
['thing','东西'],
['person','人'],
['name','名字'],
['book','书'],
['Chinese','汉语'],
['character','字'],
['desk','桌子'],
['chair','椅子'],
['thank','谢谢'],
['you are welcome','不客气'],
['good-bye','再见'],
['please','请'],
['sorry','对不起'],
['It doesnt matter','没关系'],
['be (am, is, are)','是'],
['be (am, is, are)','是'],
['be (am, is, are)','是'],
['have','有'],
['look','看'],
['listen','听'],
['speak','说话'],
['read','读'],
['write','写'],
['see','看见'],
['call','叫'],
['come','来'],
['return','回'],
['go','去'],
['eat','吃'],
['drink','喝'],
['sleep','睡觉'],
['call up','打电话'],
['do','做'],
['buy','买'],
['open','开'],
['sit','坐'],
['live','住'],
['study','学习'],
['work','工作'],
['rain','下雨'],
['love','爱'],
['love, like','喜欢'],
['want','想'],
['know','认识'],
['can','会'],
['can, be able to','能'],
['can, be able to','能'],
['good','好'],
['big','大']
])

for(let i=0; i<text.length; i++) {
    translation.forEach(function(value, key){
        if (text[i].innerHTML.includes(" "+key+" ")) {
            text[i].innerHTML = text[i].innerHTML.replace(" "+key+" ", " "+value+" ");
        }
    })
}

